server:
  port: 8080

app:
  name: "ToDoManager"
  version: "1.0"

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8081

logging:
  level:
    com.mipt.lysaleksandr.todomanager: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80