name: current date and time

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  datetime:
    runs-on: ubuntu-latest
    steps:
    - name: Show current date and time
      run: |
        echo "Current DateTime: $(date '+%Y-%m-%d %H:%M:%S %Z')"
